import api from "./api";

export const HAR = "ATL-HAR-00217";

// Each step: route to show, lens accent, narration, and an optional scripted action run on entry.
export const STORY = [
  { route: "/", lens: "oversight", title: "One Matter. One history. Three perspectives.",
    text: "This is the Harrington Family Estate. We will follow a single consequential event — a trustee succession — as it flows through the Fiduciary, Beneficiary, and Oversight lenses without ever creating three versions of the truth.",
    action: async (ctx) => { ctx.switchMatter(HAR); await api.reset(); await ctx.refresh(HAR); } },
  { route: "/fiduciary", lens: "fiduciary", title: "The Fiduciary lens — where governed truth is operated",
    text: "James Morgan, the fiduciary officer, sees the current governed state: checkpoint v2.0, Robert Harrington serving as trustee. A new source has just arrived." },
  { route: "/fiduciary/change", lens: "fiduciary", title: "Changes begin with source-linked evidence",
    text: "The Successor Acceptance & Resignation Instrument is captured. Atlas extracts operational facts as claims — but an AI observation is not a governed fact.",
    action: async (ctx) => { await api.uploadSource(HAR, null, "Successor Acceptance & Resignation Instrument.pdf"); await ctx.refresh(HAR); } },
  { route: "/fiduciary/change", lens: "fiduciary", title: "Human governance sits between AI and institutional truth",
    text: "The officer verifies each claim against the governing instrument — Trust Agreement, Article VII §3.2. Only now do the claims become verified facts.",
    action: async (ctx) => { await api.verifyClaims(HAR); await ctx.refresh(HAR); } },
  { route: "/fiduciary/change", lens: "fiduciary", title: "A ChangeSet is a proposal, not the current state",
    text: "Verified claims are assembled into a controlled ChangeSet: Robert → INACTIVE, Maya → CURRENT, checkpoint v2.0 → v3.0. Before Atlas, the firm could show Maya was named trustee. After Atlas, it can prove when her authority became effective, why it was valid, and who verified it.",
    action: async (ctx) => { await api.createChangeset(HAR); await ctx.refresh(HAR); } },
  { route: "/fiduciary/change", lens: "fiduciary", title: "A new governed state is established",
    text: "Approval releases checkpoint v3.0. Maya Harrington is the current trustee; v2.0 is preserved as history. Atlas links this into one Consequential Event with downstream responsibilities.",
    action: async (ctx) => { await api.approveChangeset(HAR); await ctx.refresh(HAR); } },
  { route: "/fiduciary/timeline", lens: "fiduciary", title: "The Matter Timeline is causal history, not an activity feed",
    text: "One event links trigger, source, verification, state transition, conduct, obligation, beneficiary impact, and evidence — with effective, recorded, verified, and released times kept distinct." },
  { route: "/fiduciary/obligations", lens: "fiduciary", title: "Consequences create obligations with owners",
    text: "The succession created an OPEN obligation: notify affected beneficiaries by 2026-06-08. Every obligation has an owner and a lifecycle." },
  { route: "/beneficiary", lens: "beneficiary", title: "The Beneficiary lens — the same truth, in plain language",
    text: "Sarah Harrington sees what changed (Maya is now her trustee) and what did not (her rights and distributions). No jargon, no reconstruction, no action required." },
  { route: "/beneficiary/rac", lens: "beneficiary", title: "The R.A.C. — Relationship-and-Conduct Statement — is a projection, not a second reality",
    text: "An R.A.C. is a plain-language record of what happened, under what authority, on what evidence, and what it means for its reader. It answers the beneficiary's questions from the same governed history the fiduciary operates. It explains conduct — it does not adjudicate it." },
  { route: "/oversight", lens: "oversight", title: "The Oversight lens — supervision by exception",
    text: "Patricia Vance supervises a book of trusts. Harrington surfaces in the attention queue because an obligation is open — not because someone filed a report." },
  { route: "/oversight/matter", lens: "oversight", title: "Understand why a Matter surfaced without rebuilding it",
    text: "Source, verification, conduct, obligation, and communication status are all visible. The supervisor escalates for resolution — oversight is part of the operating loop.",
    action: async (ctx) => { const m = await api.getMatter(HAR); const ob = m.obligations.find((o) => o.id === "ob_notice"); if (ob && ob.status === "OPEN") await api.obligationAction(HAR, "ob_notice", { action: "escalate" }); await ctx.refresh(HAR); } },
  { route: "/fiduciary/communications", lens: "fiduciary", title: "Close the loop with a source-linked communication",
    text: "The officer sends the beneficiary notice. The letter is attached as completion evidence, the obligation is satisfied, and a new checkpoint v4.0 is released.",
    action: async (ctx) => { const m = await api.getMatter(HAR); const ob = m.obligations.find((o) => o.id === "ob_notice"); if (ob && ob.status !== "SATISFIED") await api.sendCommunication(HAR, { to: "Sarah Harrington", type: "Beneficiary Notice" }); await ctx.refresh(HAR); } },
  { route: "/fiduciary/rac", lens: "fiduciary", title: "Portable evidence partners can take away",
    text: "Three R.A.C. perspectives and a chain of Evidence Instruments — v2.0, v3.0, v4.0 — each knowing its predecessor. Export any of them as an audit-ready PDF." },
  { route: "/", lens: "oversight", title: "Back where we began",
    text: "One consequential event. One governed history. Three audiences, each served by a lens — never by a separate copy of the truth. Built for trust. Designed for stewardship." },
];
